/*
 * Copyright @ 2018 - present 8x8, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jitsi.nlj;

import org.jitsi.nlj.rtp.VideoRtpPacket;
import org.jitsi.nlj.util.Bandwidth;
import org.jitsi.rtp.rtp.RtpPacket;
import org.jitsi.utils.ArrayUtils;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.NavigableMap;
import java.util.TreeMap;

/**
 * Represents a collection of {@link RtpLayerDesc}s that encode the same
 * media source. This specific implementation provides webrtc simulcast stream
 * suspension detection.
 *
 * We take the definition of "Media Source" from RFC 7656.  It takes a single
 * logical source of media, which might be represented by multiple encoded streams.
 *
 * @author George Politis
 */
public class MediaSourceDesc
{
    /**
     * The {@link RtpEncodingDesc}s that this {@link MediaSourceDesc}
     * possesses, ordered by their subjective quality from low to high.
     */
    private final RtpEncodingDesc[] rtpEncodings;

    /**
     * A string which identifies the owner of this source (e.g. the endpoint
     * which is the sender of the source).
     */
    private final String owner;

    /**
     * A string which identifies this source.
     */
    private final String sourceName;

    /**
     * The {@link VideoType} signaled for this media source (defaulting to {@code CAMERA} if nothing has been
     * signaled).
     */
    private VideoType videoType;

    /**
     * Whether this is a synthetic source, i.e. one generated by the bridge rather than sent by an endpoint.
     */
    private final boolean synthetic;

    /**
     * Current single-list view of all the encodings' layers.
     */
    private List<RtpLayerDesc> layers;

    /**
     * Allow the lookup of a layer by the encoding id of a received packet.
     */
    private final Map<Long, RtpLayerDesc> layersById = new HashMap<>();

    /**
     * Allow the lookup of a layer by index.
     */
    private final NavigableMap<Integer, RtpLayerDesc> layersByIndex = new TreeMap<>();

    public MediaSourceDesc(RtpEncodingDesc[] rtpEncodings, String owner, String sourceName)
    {
        this(rtpEncodings, owner, sourceName, VideoType.CAMERA, false);
    }

    public MediaSourceDesc(
        RtpEncodingDesc[] rtpEncodings,
        String owner,
        String sourceName,
        VideoType videoType)
    {
        this(rtpEncodings, owner, sourceName, videoType, false);
    }

    public MediaSourceDesc(
        RtpEncodingDesc[] rtpEncodings,
        String owner,
        String sourceName,
        VideoType videoType,
        boolean synthetic)
    {
        this.rtpEncodings = rtpEncodings;
        this.owner = owner;
        this.sourceName = sourceName;
        this.videoType = videoType;
        this.synthetic = synthetic;
        updateLayerCache();
    }

    public RtpEncodingDesc[] getRtpEncodings()
    {
        return rtpEncodings;
    }

    public String getOwner()
    {
        return owner;
    }

    public String getSourceName()
    {
        return sourceName;
    }

    public VideoType getVideoType()
    {
        return videoType;
    }

    public void setVideoType(VideoType videoType)
    {
        this.videoType = videoType;
    }

    public boolean isSynthetic()
    {
        return synthetic;
    }

    /**
     * Get a view of the source's RTP layers, in quality order.
     */
    public synchronized List<RtpLayerDesc> getRtpLayers()
    {
        return layers;
    }

    /**
     * Update the layer cache.  Should be synchronized on {@code this}.
     */
    private void updateLayerCache()
    {
        layersById.clear();
        layersByIndex.clear();
        List<RtpLayerDesc> tempLayers = new ArrayList<>();

        for (RtpEncodingDesc encoding : rtpEncodings)
        {
            for (RtpLayerDesc layer : encoding.getLayers())
            {
                layersById.put(encoding.encodingId(layer), layer);
                layersByIndex.put(layer.getIndex(), layer);
                tempLayers.add(layer);
            }
        }
        layers = Collections.unmodifiableList(tempLayers);
    }

    /**
     * Gets the last "stable" bitrate (in bps) of the encoding of the specified
     * index. The "stable" bitrate is measured on every new frame and with a
     * 5000ms window.
     *
     * If the bitrate for the specified index is 0, return bitrate of the highest-
     * index layer less than the index with a non-zero bitrate.
     *
     * @return the last "stable" bitrate (bps) of the encoding with a non-zero rate
     * at or below the specified index.
     */
    public synchronized Bandwidth getBitrate(long nowMs, int idx)
    {
        for (Map.Entry<Integer, RtpLayerDesc> entry : layersByIndex.headMap(idx, true).descendingMap().entrySet())
        {
            Bandwidth bitrate = entry.getValue().getBitrate(nowMs);
            if (bitrate.getBps() > 0)
            {
                return bitrate;
            }
        }
        return Bandwidth.ZERO;
    }

    public synchronized boolean hasRtpLayers()
    {
        return !layers.isEmpty();
    }

    public synchronized int numRtpLayers()
    {
        return layersByIndex.size();
    }

    public long getPrimarySSRC()
    {
        return rtpEncodings[0].getPrimarySSRC();
    }

    public synchronized RtpLayerDesc getRtpLayerByQualityIdx(int idx)
    {
        return layersByIndex.get(idx);
    }

    public synchronized Collection<RtpLayerDesc> findRtpLayerDescs(VideoRtpPacket videoRtpPacket)
    {
        if (ArrayUtils.isNullOrEmpty(rtpEncodings))
        {
            return Collections.emptyList();
        }
        List<RtpLayerDesc> found = new ArrayList<>();
        for (Long encodingId : videoRtpPacket.getEncodingIds())
        {
            RtpLayerDesc layer = layersById.get(encodingId);
            if (layer != null)
            {
                found.add(layer);
            }
        }
        return found;
    }

    public synchronized RtpEncodingDesc findRtpEncodingDesc(long ssrc)
    {
        for (RtpEncodingDesc encoding : rtpEncodings)
        {
            if (encoding.hasSsrc(ssrc))
            {
                return encoding;
            }
        }
        return null;
    }

    public synchronized RtpLayerDesc[] getEncodingLayers(long ssrc)
    {
        RtpEncodingDesc enc = findRtpEncodingDesc(ssrc);
        if (enc == null)
        {
            return new RtpLayerDesc[0];
        }
        RtpLayerDesc[] copies = new RtpLayerDesc[enc.getLayers().length];
        for (int i = 0; i < copies.length; i++)
        {
            copies[i] = enc.getLayers()[i].copy();
        }
        return copies;
    }

    public synchronized void setEncodingLayers(RtpLayerDesc[] layers, long ssrc)
    {
        RtpEncodingDesc enc = findRtpEncodingDesc(ssrc);
        if (enc == null)
        {
            return;
        }
        enc.setLayers(layers);
        updateLayerCache();
    }

    /**
     * Clone an existing media source desc, inheriting layer descs' statistics.
     */
    public synchronized MediaSourceDesc copy()
    {
        RtpEncodingDesc[] encodingsCopy = new RtpEncodingDesc[this.rtpEncodings.length];
        for (int i = 0; i < encodingsCopy.length; i++)
        {
            encodingsCopy[i] = this.rtpEncodings[i].copy();
        }
        return new MediaSourceDesc(encodingsCopy, this.owner, this.sourceName, this.videoType, this.synthetic);
    }

    @Override
    public String toString()
    {
        StringBuilder encodingsString = new StringBuilder();
        for (int i = 0; i < rtpEncodings.length; i++)
        {
            if (i > 0)
            {
                encodingsString.append(",");
            }
            encodingsString.append(rtpEncodings[i]);
        }
        return "MediaSourceDesc[name=" + sourceName + " owner=" + owner + ", videoType=" + videoType + ", " +
            "synthetic=" + synthetic + ", encodings=" + encodingsString + "]";
    }

    /**
     * Checks whether the given SSRC matches this source's {@link #getPrimarySSRC()}.
     * This is mostly useful only for determining quickly whether two source
     * descriptions describe the same source; other functions (probably {@link #hasSsrc}) should be used
     * to match received media packets.
     *
     * @param ssrc the SSRC to match.
     * @return {@code true} if the specified {@code ssrc} is the primary SSRC
     * for this source.
     */
    public boolean matches(long ssrc)
    {
        return rtpEncodings.length > 0 && rtpEncodings[0].getPrimarySSRC() == ssrc;
    }

    /**
     * Checks whether any encoding of this source has this {@code ssrc}
     */
    public synchronized boolean hasSsrc(long ssrc)
    {
        for (RtpEncodingDesc encoding : rtpEncodings)
        {
            if (encoding.hasSsrc(ssrc))
            {
                return true;
            }
        }
        return false;
    }

    /**
     * Clone an array of media source descriptions.
     */
    public static MediaSourceDesc[] copy(MediaSourceDesc[] sources)
    {
        MediaSourceDesc[] copies = new MediaSourceDesc[sources.length];
        for (int i = 0; i < sources.length; i++)
        {
            copies[i] = sources[i].copy();
        }
        return copies;
    }

    public static Collection<RtpLayerDesc> findRtpLayerDescs(MediaSourceDesc[] sources, VideoRtpPacket packet)
    {
        List<RtpLayerDesc> result = new ArrayList<>();
        for (MediaSourceDesc source : sources)
        {
            result.addAll(source.findRtpLayerDescs(packet));
        }
        return result;
    }

    public static MediaSourceDesc findRtpSourceByPrimary(MediaSourceDesc[] sources, long ssrc)
    {
        for (MediaSourceDesc source : sources)
        {
            if (source.matches(ssrc))
            {
                return source;
            }
        }
        return null;
    }

    public static MediaSourceDesc findRtpSource(MediaSourceDesc[] sources, long ssrc)
    {
        for (MediaSourceDesc source : sources)
        {
            if (source.hasSsrc(ssrc))
            {
                return source;
            }
        }
        return null;
    }

    public static MediaSourceDesc findRtpSource(MediaSourceDesc[] sources, RtpPacket packet)
    {
        return findRtpSource(sources, packet.getSsrc());
    }

    public static Integer findRtpEncodingId(MediaSourceDesc[] sources, VideoRtpPacket packet)
    {
        for (MediaSourceDesc source : sources)
        {
            RtpEncodingDesc encoding = source.findRtpEncodingDesc(packet.getSsrc());
            if (encoding != null)
            {
                return encoding.getEid();
            }
        }
        return null;
    }
}
